### ISSUE TITLE
Some editor

### ISSUE THREAD

**Issue by vd3d** [MichalWierzbinski/cosmosdb-emulator-gremlin#1]
Hi,

thanks for the sample, its really helpful :-)

But I have a question, is there a way to view/edit the content of the graph ?

thanks

**Comment by xultaeculcis** [comment]
Hi,

Thank you for the kind words :)

If you want to have something that looks like your standard Graph Data Explorer from the Azure Portal then the closest you can get is by using Graph Explorer from Microsoft: https://github.com/Azure-Samples/azure-cosmos-db-dotnet-graphexplorer 

However it uses Microsoft.Azure.Graphs package underneath, which is slow due to an overhead and consumes a lot more memory than Gremlin.Net. If you really want to use it you might want to rewrite the .net part with Gremlin.Net.

Other than that I really don't know about other free solutions/projects that might be able to query and visualize Cosmos DB Emulator's graphs. You might also try to implement your own solution ;)

Regards,
Michal

**Comment by vd3d** [comment]
Hi Michal,

I just found that Visual Studio Code has a an extension that support CosmosDB :

https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-cosmosdb

They are able to connect to a Gremlin DB but not yet on the emulator unfortunately :-(
See here : https://github.com/Microsoft/vscode-cosmosdb/issues/349

Thanks a lot

**Comment by xultaeculcis** [comment]
Indeed, Cosmos DB Extension for Visual Studio Code can be used to query Cosmos DB's Graph API. However due to Gremlin Endpoint on the Emulator being implemented **WITH SSL DISABLED** (I don't know why Emulator team made this decision - especially since all other APIs use SSL by default) - it is impossible to use this extension with it.

When trying to connect to database account after selecting Gremlin API account with following connection string: 
"AccountEndpoint=https://localhost:8901/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=="

You will get following error: **"Error: write EPROTO 4316:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:d:\_vsts\3\s\vendor\node\deps\openssl\openssl\ssl\record\ssl3_record.c:252:"**

So just like I mentioned earlier - your best option is to use GraphExplorer after changing the Microsoft.Azure.Graphs library to Gremlin.NET

If you have no more questions regarding this topic, then I will proceed to close this Issue in next 48 hours.

Regards,
Michal
