### ISSUE TITLE
How to finish setup?

### ISSUE THREAD

**Issue by MisinformedDNA** [MichalWierzbinski/cosmosdb-emulator-gremlin#2]
In the README, you say

> Endpoints in the sample are preconfigured to run with the Emulator. You don't have to change anything apart for db, graph and partition key property names.

So where do I setup/change db, graph and partition key?

Not working as-is:

![image](https://user-images.githubusercontent.com/1784452/54089431-c988ee00-4336-11e9-8dc4-701b63c11f9b.png)

**Comment by xultaeculcis** [comment]
Hi, 

I was able to reproduce the exception. The reason you might be getting it is most likely caused by you changing the default Gremlin port in the emulator. When you run the emulator from CMD/PowerShell you can specify the port on which the Gremlin Endpoint will be accessible (as shown in README). If you don't change it, then it will default to 8901. If you change it however - then you must update the config region in the Program.cs (line 28).
The db, graph and partition key are the names of your Database, Container and Partition Key Property that you specified while creating them via the Emulator UI. Your Graph is your Container (naming schema from Microsoft, same would apply if you were to work with Cassandra Endpoint - then your Container would be called a Table). In order for the Gremlin.Net to connect to your Graph you must first create them via the UI - otherwise it will fail. Gremlin.Net does not have a capability to create Graphs or Database accounts in your Cosmos DB account that's why it is vital to have them created before attempting to connect to them.
If the issue persists please add a detailed information regarding your setup (Emulator version, used commands, content of your Config region from Program.cs), anything really to help me recreate the exception.
